apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongodb
  namespace: springcloud
  labels:
    name: auth-mongodb
spec:
  replicas: 1
  selector:
     matchLabels:
        name: auth-mongodb
  template:
    metadata:
      labels:
        name: auth-mongodb
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: auth-mongodb
        image: sqshq/piggymetrics-mongodb
        imagePullPolicy: IfNotPresent
        env:
         - name: MONGODB_PASSWORD
           value: admin
