apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  namespace: springcloud
  labels:
    name: config
spec:
  replicas: 1
  selector:
    matchLabels:
        name: config
  template:
    metadata:
      labels:
        name: config
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: config
        image: sqshq/piggymetrics-config
        imagePullPolicy: IfNotPresent
        env:
        - name: CONFIG_SERVICE_PASSWORD
          value: admin 
