apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: springcloud
  labels:
    name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
        name: gateway
  template:
    metadata:
      labels:
        name: gateway
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: gateway
        image: sqshq/piggymetrics-gateway
        imagePullPolicy: IfNotPresent
        env:
        - name: CONFIG_SERVICE_PASSWORD
          value: admin
