apiVersion: apps/v1 
kind: Deployment
metadata:
  name: notification-service
  namespace: springcloud
  labels:
    name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
        name: notification-service 
  template:
    metadata:
      labels:
        name: notification-service
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: notification-service
        image: sqshq/piggymetrics-notification-service
        imagePullPolicy: IfNotPresent
        env:
        - name: CONFIG_SERVICE_PASSWORD
          value: admin
        - name: MONGODB_PASSWORD
          value: admin
        - name: NOTIFICATION_SERVICE_PASSWORD
          value: admin

