apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-mongodb
  namespace: springcloud
  labels:
    name: notification-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
        name: notification-mongodb
  template:
    metadata:
      labels:
        name: notification-mongodb
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: notification-mongodb
        image: sqshq/piggymetrics-mongodb
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGODB_PASSWORD
          value: admin
