apiVersion:  apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: springcloud
  labels:
    name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
        name: rabbitmq
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        imagePullPolicy: IfNotPresent
