apiVersion: apps/v1 
kind: Deployment
metadata:
  name: registry
  namespace: springcloud
  labels:
    name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
        name: registry
  selector:
    matchLabels:
        name: registry
  template:
    metadata:
      labels:
        name: registry
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: registry
        image: sqshq/piggymetrics-registry
        imagePullPolicy: IfNotPresent
        env:
        - name: CONFIG_SERVICE_PASSWORD
          value: admin

