apiVersion: v1
kind: Service
metadata:
  labels:
    name: config
  name: config
  namespace: springcloud
spec:
  type: NodePort
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
    nodePort: 30015
  selector:
    name: config
