apiVersion: v1
kind: Service
metadata:
  labels:
    name: monitoring
  name: monitoring
  namespace: springcloud
spec:
  type: NodePort
  ports:
  - name: monitor
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30012
  - name: monitor-2
    port: 8989
    protocol: TCP
    targetPort: 8989
    nodePort: 30013
  selector:
    name: monitoring
