apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq
  namespace: springcloud
spec:
  type: NodePort
  ports:
  - name: rabbitmq-1
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: rabbitmq-2
    port: 15672
    protocol: TCP
    targetPort: 15672
    nodePort: 30014
  - name: rabbitmq-3
    port: 15671
    protocol: TCP
    targetPort: 15671
  - name: rabbitmq-4
    port: 25672
    protocol: TCP
    targetPort: 25672
  - name: rabbitmq-5
    port: 4369
    protocol: TCP
    targetPort: 4369
  selector:
    name: rabbitmq
