apiVersion: v1
kind: Service
metadata:
  labels:
    name: registry
  name: registry
  namespace: springcloud
spec:
  type: NodePort
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
    nodePort: 30011
  selector:
    name: registry
